pipeline{
    agent any
    options{
        disableConcurrentBuilds()   // at a time two or more builds not allowed. wait once running pipleine executes compltes, then new build will run
        //isableConcurrentBuilds(abortPrevious: true)  //means stop running one and start new build
    }
    stages{
        stage("Build"){
            steps{
                sh "echo hello world"
            }
        }
        stage("Test"){
            steps{
                sh "echo I am from Test stage"
            }
        }
        stage("Deploy"){
            steps{
                sh "echo I am from Deploy stage"
            }
        }
    }
    //post build
    always{
        echo "I always run when pipeline running"
    }
    failure{
        echo "Pipeline is FAILED"
    }
    success {
        echo "Pipeline is Success"
    }
    regression {
        echo "It will execute if Pipeline status is failure, unstable, or aborted and the previous run was successful"
    }
}