pipeline{
    // agent any
    agent{
        label 'AGENT-1'
    }
    options{
        disableConcurrentBuilds() 
        // retry(2)    //it will retry 2 times, if pipeline failure
        timeout(time: 30, unit: 'MINUTES') //pipeline will stop/abort when specified time period
        ansiColor('xterm')
    }
    environment{
        project = 'expense'
        environment = ''
        component = ''
        region = ''
        aws_account_id = '537124943253'
    }
    parameters {
        string(name: 'component', defaultValue: 'frontend', description: 'Component name')
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'uat', 'pre-pod', 'prod'], description: 'Select environment')
        string(name: 'region', defaultValue: 'us-east-1', description: 'Region is')
        booleanParam(name: 'deploy', defaultValue: false, description: 'deploy this')
    }
    stages{
        stage("Read Vesrion"){
            steps{
                script {
                    dir('frontend-cicd/FRONTEND-CI/code'){
                        // Read the JSON file
                        def packageJson = readJSON file: 'package.json'
                        imageVersion = packageJson.version
                        // Access JSON properties
                        // echo "Version is: ${packageJson.version}"   //you can directly use this line as well
                        echo "Version is: ${imageVersion}"
                    }
                }          
            }
        }
        //install docker in jenkins agent, if u are running this satge in agent.
        stage("Build docker Image"){
            steps{
                // withCredentials([[credentialsId: 'aws-creds', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                 withCredentials([aws(credentialsId: "aws-creds")]) {
                     sh """
                        cd frontend-cicd/FRONTEND-CI
                        
                        aws ecr get-login-password --region ${params.region} | docker login --username AWS --password-stdin ${aws_account_id}.dkr.ecr.us-east-1.amazonaws.com

                        docker build -t ${aws_account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${params.ENVIRONMENT}/${params.component}:${imageVersion} .
                       
                        docker images

                        docker push ${aws_account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${params.ENVIRONMENT}/${params.component}:${imageVersion}
                    """
                }
            }
        }
        stage('Trigger Deploy to EKS') {
            when {
                expression {params.deploy}
            }
            steps {
                // Trigger the second pipeline 'FRONTEND-CD' this is path of jenkins(if it is in root level) not repo path
                build job: 'FRONTEND-CD', parameters: [
                    //these parameters or env vars passed to BACKEND-CD, u can access there
                    string(name: 'component', value: "${params.component}"),
                    string(name: 'ENVIRONMENT', value: "${params.ENVIRONMENT}"),
                    string(name: 'region', value: "${params.region}"),
                    string(name: 'version', value: "${imageVersion}")
                ], wait: true
            }
        }
    }
    post{
        //post build section
        always{
            echo "I always run when pipeline running"
            deleteDir()    //Cleans up workspace after every build.
        }
        failure{
            echo "Pipeline is FAILED"
        }
        success {
            echo "Pipeline is Success"
        }
        regression {
            echo "It will execute if Pipeline status is failure, unstable, or aborted and the previous run was successful"
        }
    }
}